name: Publish SNAPSHOT

on:
  push:
    branches:
      - main
      - develop

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and publish SNAPSHOT
        run: ./gradlew -Pversion=1.1.0-SNAPSHOT publish

      - name: Checkout maven-repo
        uses: actions/checkout@v4
        with:
          repository: deinuser/maven-repo
          path: maven-repo
          token: ${{ secrets.MAVEN_REPO_TOKEN }}

      - name: Copy published artifacts
        run: |
          mkdir -p maven-repo/repo/snapshots
          cp -r paper/api/build/repo/snapshots/* maven-repo/repo/snapshots/

      - name: Commit and push SNAPSHOT
        run: |
          cd maven-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Publish SNAPSHOT build"
            git push
          fi